title: 黄全的个人主页
page-top-title: 黄全的个人主页
top-section-bg-text: 欢迎！
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
  - static/assets/background/background_2.jpg
  - static/assets/background/background_3.jpg
  - static/assets/background/background_4.jpg
  - static/assets/background/background_5.jpg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Quan Huang 2023-2026. All Rights Reserved.'
#github-link:
 # text: Github
  #href: https://github.com/HuangQuan1124
#license-link:
 # text: License
 # href: https://github.com/HuangQuan1124/HuangQuan1124.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: 主页
    title: 黄全&ensp;|&ensp;南昌航空大学 信息工程学院（人工智能学院）
    href: '#page-top' # Default to '#<id>' if not specified
  - id: news
    nav: 最新动态
    title: 最新动态
    icon: bi-play-btn-fill
  - id: projects
    nav: 项目经历
    title: 项目经历
    icon: bi-octagon-fill
  - id: publications
    nav: 学术成果
    title: 学术成果
    icon: bi-file-text-fill
  - id: awards
    nav: 荣誉与奖励
    title: 荣誉与奖励
    icon: bi-award-fill
